on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY_URI: 541261779827.dkr.ecr.us-east-1.amazonaws.com/linkagebackend
  TASK_DEFINITION_NAME: LinkageTaskDefinition  # Name of your task definition
  NEW_SECURITY_GROUP_ID: sg-05bc3dff8e3341287  # New security group ID

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI

    - name: Build Docker image
      run: |
        docker build -t $ECR_REPOSITORY_URI:latest .

    - name: Push Docker image to ECR
      run: |
        docker push $ECR_REPOSITORY_URI:latest

    - name: Update ECS Task Definition Security Group
      id: update-task
      run: |
        # Fetch the current Revision 1 of the task definition
        CURRENT_TASK=$(aws ecs describe-task-definition \
          --task-definition ${{ env.TASK_DEFINITION_NAME }}:1)

        # Modify the security group
        UPDATED_TASK=$(echo "$CURRENT_TASK" | jq --arg sg_id "${{ env.NEW_SECURITY_GROUP_ID }}" '
          .taskDefinition |
          del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy) |
          .networkConfiguration.awsvpcConfiguration.securityGroups = [$sg_id]
        ')

        # Save the updated task definition and re-register it
        echo "$UPDATED_TASK" > updated-task-def.json
        aws ecs register-task-definition --cli-input-json file://updated-task-def.json

    - name: Update ECS Service to Use Task Definition Revision 1
      run: |
        # Always point the ECS service to use Revision 1
        aws ecs update-service \
          --cluster LinkageCluster \
          --service express-backend-service-v2 \
          --task-definition ${{ env.TASK_DEFINITION_NAME }}:1 \
          --force-new-deployment
